// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 本地 SQLite，路径相对项目根目录；.env 缺失时用默认值兜底
    url: process.env["DATABASE_URL"] ?? "file:./prisma/dev.db",
  },
});
